wordpress:
  #image: wordpress
  build: .
  mem_limit: 256m
  ports:
    - 80:80
  environment:
    - WORDPRESS_DB_HOST=mysql.wnews.org.au
    - WORDPRESS_DB_USER=
    - WORDPRESS_DB_PASSWORD=
    - WORDPRESS_DB_NAME=basepatterns_wp
    - WORDPRESS_TABLE_PREFIX=wp_z5xguu_
